stakeholders_client:
    resource: "@StakeholdersClientBundle/Controller/"
    type:     annotation
    prefix:   /
    
stakeholders_api:
    resource: "@StakeholdersApiBundle/Controller/"
    type:     annotation
    prefix:   /v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc
 
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
  
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    options:
        expose: true
    
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /oauth/v2

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /access/connect
    options:
        expose: true

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /access/connect
    options:
        expose: true

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /access/connect
    options:
        expose: true

facebook_login:
    path: /access/login/check-facebook
    
user:
    type: rest
    resource: Stakeholders\ApiBundle\Controller\UserController
    prefix: /v1
    options:
        expose: true

influencer:
    type: rest
    resource: Stakeholders\ApiBundle\Controller\InfluencerController
    prefix: /v1
    options:
        expose: true
        
user_register:
    type: annotation
    resource: Stakeholders\ApiBundle\Controller\RegisterController
    prefix: /oauth/v2
    options:
        expose: true