security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
        ROLE_AGENCY: ROLE_USER
        ROLE_INFLUENCER: ROLE_USER
        ROLE_CUSTOMER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_CUSTOMER, ROLE_INFLUENCER, ROLE_AGENCY, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        stakeholders_oauth:
            id: stakeholders_client.oauth_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        api:
            pattern: ^/v1
            fos_oauth: true
            stateless: true
            anonymous: false
            
        api_register:
            pattern: ^/v1/user/register
            anonymous: true
            security: false
            
        api_social_auth:
            pattern: ^/v1/social-login
            anonymous: true
            security: false
            
        api_oauth:
            pattern: ^/access/oauth/fb
            anonymous: true
            security: false

        social_auth:
            pattern: ^/access
            anonymous: true
            oauth:
                provider: fos_userbundle
                login_path: /access/connect
                check_path: /access/connect
                resource_owners: 
                    facebook: /access/login/check-facebook
                login_path: /login
                use_forward: false
                success_handler: stakeholders_api.social_auth_security
                
                oauth_user_provider:
                    service: hwi_oauth.user.provider #hwi_oauth.user.provider.entity
            
        client:
            pattern: ^/app
            anonymous: false
            guard:
               authenticators:
                   - stakeholders_client.oauth_authenticator
            logout: true
        main:
            pattern: ^/block
            security: false
            
    access_control:
        - { path: ^/v1, roles: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/social-auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/access, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       