services:
    stakeholders_client.oauth_authenticator:
        class: Stakeholders\ClientBundle\Security\OAuthAuthenticator
        arguments: ["@service_container"]
        
    stakeholders_client.oauth_user_provider:
        class: Stakeholders\ClientBundle\Security\User\OAuthUserProvider
        arguments: ["@service_container"]