Stakeholders\ApiBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        firstName:
            expose: true
        lastName:
            expose: true
        photo:
            expose: true
        brief:
            expose: true
        isApproved:
            expose: true